services:
  backend:
    image: photocatalog-backend:${APP_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photocatalog-api
    ports:
      - "${EXTERNAL_PORT:-5000}:8080"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - photocatalog-network

networks:
  photocatalog-network:
    driver: bridge