services:
 backend:
   image: photocatalog-backend:${APP_VERSION:-latest}
   build:
     context: .
     dockerfile: Dockerfile
   container_name: photocatalog-backend
   ports:
     - "${EXTERNAL_PORT:-5000}:8000"
   volumes:
     - ./data:/app/data
   environment:
     - ASPNETCORE_ENVIRONMENT=Develoment
     - ASPNETCORE_URLS=http//+:8000
   restart: unless-stopped
   networks:
     - photocatalog-networks
networks:
  photocatalog-networks:
    driver: bridge