-- Важно: При каждом открытии соединения (ADO.NET) вызывать PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS "Photos" (
	"Id" INTEGER NOT NULL,
	"RealPath" TEXT NOT NULL UNIQUE,
	"FileHash" TEXT,
	"Width" INTEGER,
	"Height" INTEGER,
	"AddedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("Id")
);

CREATE TABLE IF NOT EXISTS "Folders" (
	"Id" INTEGER NOT NULL,
	"Name" TEXT NOT NULL,
	"ParentFolderId" INTEGER,
	PRIMARY KEY("Id"),
	FOREIGN KEY ("ParentFolderId") REFERENCES "Folders"("Id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "Albums" (
	"Id" INTEGER NOT NULL,
	"Name" TEXT NOT NULL,
	"FolderId" INTEGER,
	PRIMARY KEY("Id"),
	FOREIGN KEY ("FolderId") REFERENCES "Folders"("Id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "Tags" (
	"id" INTEGER NOT NULL,
	"Name" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "AlbumPhotos" (
	"AlbumId" INTEGER NOT NULL,
	"PhotoId" INTEGER NOT NULL,
	PRIMARY KEY("AlbumId", "PhotoId"),
	FOREIGN KEY ("AlbumId") REFERENCES "Albums"("Id")
	ON UPDATE NO ACTION ON DELETE CASCADE,
	FOREIGN KEY ("PhotoId") REFERENCES "Photos"("Id")
	ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "PhotoTags" (
	"PhotoId" INTEGER NOT NULL,
	"TagId" INTEGER NOT NULL,
	PRIMARY KEY("PhotoId", "TagId"),
	FOREIGN KEY ("PhotoId") REFERENCES "Photos"("Id")
	ON UPDATE NO ACTION ON DELETE CASCADE,
	FOREIGN KEY ("TagId") REFERENCES "Tags"("id")
	ON UPDATE NO ACTION ON DELETE CASCADE
);
