set time zone 'Europe/Moscow';

DO
$body$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_user WHERE username = 'app') THEN
            CREATE USER app WITH PASSWORD '1234';
        END IF;

    END ;
$body$;


GRANT CONNECT ON DATABASE photoCatalog TO app;
GRANT USAGE ON SCHEMA public TO app;
GRANT CREATE ON SCHEMA public TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app;

CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
GRANT EXECUTE ON FUNCTION pg_stat_statements(IN boolean) TO app;